defaults: &defaults
  beginning_of_aliadas_day: 7 # Beginning of bussines day
  end_of_aliadas_day: 21 # End of business day
  hours_before_service: 1 # Minimal amount of time it takes an aliada to reach a service destination
  hours_after_service: 1 # Minimal amount of time after a service is done needed for each aliada
  time_horizon_days: 30 # How far in the future we build schedules and look for datetime data

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
