defaults: &defaults
  beginning_of_aliadas_day: 13 # Beginning of bussines day in UTC, or 7 am in Mexico City Time
  end_of_aliadas_day: 3 # End of business day, or 9 pm in Mexico City Time
  businessday_hours: 14 # Make sure to update this if you update the beginning_of_aliadas_day and end_of_aliadas_day

  hours_before_service: 1 # Minimal amount of time it takes an aliada to reach a service destination
  hours_after_service: 1 # Minimal amount of time after a service is done needed for each aliada
  time_horizon_days: 30 # How far in the future we build schedules and look for datetime data
  payment_providers: [
    ['Tarjeta con Conekta', 'ConektaCard'], 
    ['Método de pago de prueba', 'TestPaymentMethod'], 
  ]
  #
  # Careful while editing the text here as it determines looks on the frontend
  hours_space_room: [
    { hours: 3,   text: '<b>3h</b>     ~55m²    (1 cuarto)'},
    { hours: 3.5, text: '<b>3.5h</b>  ~65m²   (1 cuarto)'},
    { hours: 4,   text: '<b>4h</b>     ~75m²    (2 cuartos)'},
    { hours: 4.5, text: '<b>4.5h</b>  ~90m²   (2-3 cuartos)'},
    { hours: 5,   text: '<b>5h</b>     ~105m²   (3 cuartos)'},
    { hours: 5.5, text: '<b>5.5h</b>  ~120m²  (3 cuartos)'},
    { hours: 6,   text: '<b>6h</b>     ~135m²   (+3 cuartos)'},
    { hours: 6.5, text: '<b>6.5h</b>  ~150m²  (+3 cuartos)'},
    { hours: 7,   text: '<b>7h</b>     ~165m²   (+3 cuartos)'},
    { hours: 8,   text: '<b>8h</b>     ~180m²  (+3 cuartos)'}  
  ]
  bedrooms_multiplier: 1 # to get hours
  bathrooms_multiplier: 0.5 # to get hours
  minimum_hours_service: 3
  cost_per_hour: 65
  booking_for_tomorrow_limit: 23 # After this hour you cant book a service for tomorrow, in UTC or 5 pm in Mexico City Time

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

staging:
  <<: *defaults
